[package]
name = "stellaris_map_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
imageproc = "0.24.0"
pdx_parser_core = { path = "../pdx_parser_core" }
