name: Deploy Github Pages

permissions:
    id-token: write
    pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        run: |
          rustup update
          rustup default
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build WASM
        working-directory: ./cartographer_web
        run: wasm-pack build --target web --release
      - uses: actions/setup-node@v4
      - name: Install node dependencies
        working-directory: ./cartographer_web
        run: npm install
      - name: Build Vue
        working-directory: ./cartographer_web
        run: npm run build
      - name: Creating artifact
        working-directory: ./cartographer_web/dist
        run: tar -cvf artifact.tar *
      - uses: actions/upload-artifact@v4
        with:
          name: "github-pages"
          path: "./cartographer_web/dist/artifact.tar"
          retention-days: 1
          if-no-files-found: error
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
